### ISSUE TITLE
Need a release for OPK Configurator to work

### ISSUE THREAD

**Issue by rjcorwin** [jywarren/opk-dylos-cli#5]
The opk configurator requires that a repo have a release that it can download, specifically the tar.gz that a github release generates. The url to that tar.gz then needs to be added to packages.openpipekit.org.

**Comment by jywarren** [comment]
https://github.com/jywarren/opk-dylos-cli/releases/tag/v0.0.1 cool!

**Comment by rjcorwin** [comment]
Nice, I added the link to the tar.gz as the download url on the packages page for this CLI http://packages.openpipekit.org/node/16
